"""Removed answer field

Revision ID: 796fe9a8e83e
Revises: 6b480021a296
Create Date: 2024-06-19 15:47:46.784144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796fe9a8e83e'
down_revision = '6b480021a296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_desc', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_details', schema=None) as batch_op:
        batch_op.drop_column('answer_desc')

    # ### end Alembic commands ###
