"""Initial mi

Revision ID: 919301740b91
Revises: 2a6bc398e0ca
Create Date: 2024-06-17 12:47:13.073373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919301740b91'
down_revision = '2a6bc398e0ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'topic', ['topic_id'], ['id'])
        batch_op.drop_column('topic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('topic_id')

    # ### end Alembic commands ###
