"""updated workspace

Revision ID: 43111b91cea3
Revises: 796fe9a8e83e
Create Date: 2024-06-19 16:00:55.644173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43111b91cea3'
down_revision = '796fe9a8e83e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_details', schema=None) as batch_op:
        batch_op.alter_column('workspace_practice_seq',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_details', schema=None) as batch_op:
        batch_op.alter_column('workspace_practice_seq',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
