"""Increase length of feedback and question columns

Revision ID: 4d6244803fe5
Revises: 919301740b91
Create Date: 2024-06-19 15:29:47.067775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6244803fe5'
down_revision = '919301740b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_details', schema=None) as batch_op:
        batch_op.alter_column('answer_desc',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_details', schema=None) as batch_op:
        batch_op.alter_column('answer_desc',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
